<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="View\Resorsus\Assets\Images\Icons\DoctorIcon.png" />
    <None Remove="View\Resorsus\Assets\Images\Login_Background_Img.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLL\BLL.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\Resorsus\Assets\Images\Icons\DoctorIcon.png" />
    <Resource Include="View\Resorsus\Assets\Images\Login_Background_Img.png" />
  </ItemGroup>

</Project>
